services:

  app:
    build:
      context: .
    container_name: kata_user_app
    environment:
        - PYTHONPATH=/app/src
        - DB_NAME=user_db
        - DB_USER=postgres
        - DB_PASSWORD=password
        - DB_HOST=db
        - DB_PORT=5432

    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres
    container_name: kata_user_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db

    ports:
      - 6001:5432

    volumes:
      - kata_user_postgres_data:/var/lib/postgresql/data

volumes:
  kata_user_postgres_data:
